### ISSUE TITLE
java.lang.RuntimeException: Unable to start service org.qiyi.pluginlibrary.component.ServiceProxy1            

### ISSUE THREAD

**Issue by blueway** [iqiyi/Neptune#5]
```html
java.lang.RuntimeException: Unable to start service org.qiyi.pluginlibrary.component.ServiceProxy1
                                  @d2e4d84 with Intent { act=org.qiyi.plugin.library.START_PLUGIN cmp=com.soo.cool.flow/org.qiyi.pl
                                  uginlibrary.component.ServiceProxy1 (has extras) }: java.lang.IllegalStateException: pluginLiteInf
                                  o is null when launchPlugin com.android.view.mens
  2918         install_plugin  I  [ PluginInstaller ] : install success and remove pkg:com.android.view.mens
  2738        ActivityManager  W  getRunningAppProcesses: caller 10542 does not hold REAL_GET_TASKS; limiting output
  2918         install_plugin  I  [ PluginPackageManagerNative ] : remove empty action list of com.android.view.mens
  3075             System.err  W  	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2935)
  2918         runtime_plugin  I  [ ComponentFinder ] : matchServiceProxyByFeature:org.qiyi.pluginlibrary.component.ServiceProxy1
  3075             System.err  W  	at android.app.ActivityThread.access$2100(ActivityThread.java:156)
  3075             System.err  W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
  3075             System.err  W  	at android.os.Handler.dispatchMessage(Handler.java:102)
  3075             System.err  W  	at android.os.Looper.loop(Looper.java:135)
  3075             System.err  W  	at android.app.ActivityThread.main(ActivityThread.java:5282)
  3075             System.err  W  	at java.lang.reflect.Method.invoke(Native Method)
  3075             System.err  W  	at java.lang.reflect.Method.invoke(Method.java:372)
  3075             System.err  W  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
  3075             System.err  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
  3075             System.err  W  Caused by: java.lang.IllegalStateException: pluginLiteInfo is null when launchPlugin com.android.view.mens
  3075             System.err  W  	at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:533)
  3075             System.err  W  	at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:422)
  3075             System.err  W  	at org.qiyi.pluginlibrary.component.ServiceProxy1.onStartCommand(ServiceProxy1.java:227)
  3075             System.err  W  	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2918)

```

**Comment by zjupure** [comment]
提供下详细的log，看一下pluginLiteInfo为啥没有获得到值

**Comment by blueway** [comment]
不是每次都这样

**Comment by blueway** [comment]
```html

 

 install_plugin  I  [ PluginInstallerService ] : sendMessage MSG_ACTION_QUIT
  2970         install_plugin  I  [ PluginPackageManagerNative ] : onActionComplete with com.android.view.mens, errorCod
                                  e:2
 
 
 
  3075         runtime_plugin  I  [ PluginPackageManagerNative ] : getPackageInfo, service is disconnected, need rebind
  3075         runtime_plugin  I  [ PluginPackageManager ] : [warning] sPluginInfoProvider is null
 
 
 
  2918         install_plugin  I  [ PluginPackageManagerNative ] : onActionComplete with com.android.view.mens, errorCod
                                  e:2
  2918         install_plugin  I  [ PluginPackageManagerNative ] : com.android.view.mens has 1 action in list!
  3075         runtime_plugin  I  [ PluginPackageManager ] : [warning] sPluginInfoProvider is null
  2918         install_plugin  I  [ PluginPackageManagerNative ] : get and remove first action:PluginInstallAction:  has IInstallCal
                                  lBack: true packageName: com.android.view.mens plugin_ver: 0.8.1 plugin_gray_version: 
                                   
  3075         runtime_plugin  I  [ PluginManager ] : pluginLiteInfo is null packageName: com.android.view.mens
  2918         install_plugin  I  [ PluginPackageManagerNative ] : start find can execute action ...
  2918         install_plugin  I  [ PluginPackageManagerNative ] : remove empty action list of com.android.view.mens
  3014         install_plugin  I  [ PluginPackageManagerNative ] : onActionComplete with com.android.view.mens, errorCod
                                  e:2

```

**Comment by zjupure** [comment]
fixed in 2.7.0 release
