### ISSUE TITLE
小米mix2无法打开插件，不闪退

### ISSUE THREAD

**Issue by shijiacheng** [iqiyi/Neptune#6]
I/runtime_plugin: [ ComponentFinder ] : matchServiceProxyByFeature:org.qiyi.pluginlibrary.component.ServiceProxy1

**Comment by zjupure** [comment]
有详细的log信息吗？最后执行到哪一步了

**Comment by shijiacheng** [comment]
> 有详细的log信息吗？最后执行到哪一步了

就是提示插件安装成功，然后打不开

10-09 15:09:31.795 1623-3637/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.shijc.neptunedemo/com.shijc.neptunedemo.HostMainActivity/1
10-09 15:09:31.796 1623-3637/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.shijc.neptunedemo/com.shijc.neptunedemo.HostMainActivity/1
10-09 15:09:31.800 1623-2073/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.shijc.neptunedemo/com.shijc.neptunedemo.HostMainActivity/1
10-09 15:09:31.922 1623-1767/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
10-09 15:09:31.922 740-740/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.shijc.neptunedemo pid = 8708
10-09 15:09:31.922 740-740/? E/ANDR-IOP: event data pool ran empty
10-09 15:09:32.169 1623-2073/? E/LocationManagerService: provider request: gps ProviderRequest[OFF]
10-09 15:09:32.804 8822-9200/? E/NFC: register nfcservice enable receiver
10-09 15:09:32.810 8822-9200/? E/libc: Access denied finding property "ro.serialno"
10-09 15:09:32.926 9207-9207/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.shijc.neptunedemo:plugin1, PID: 9207
                                                 java.lang.RuntimeException: Unable to start service org.qiyi.pluginlibrary.component.ServiceProxy1@d68f884 with Intent { act=org.qiyi.plugin.library.START_PLUGIN cmp=com.shijc.neptunedemo/org.qiyi.pluginlibrary.component.ServiceProxy1 (has extras) }: java.lang.IllegalStateException: pluginLiteInfo is null when launchPlugin com.shijc.search
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3596)
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:171)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6699)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
                                                  Caused by: java.lang.IllegalStateException: pluginLiteInfo is null when launchPlugin com.shijc.search
                                                     at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:533)
                                                     at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:422)
                                                     at org.qiyi.pluginlibrary.component.ServiceProxy1.onStartCommand(ServiceProxy1.java:227)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3576)
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:171) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6699) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
10-09 15:09:34.795 741-830/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
                                                       return value 2
10-09 15:09:35.526 9237-9237/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.shijc.neptunedemo:plugin1, PID: 9237
                                                 java.lang.RuntimeException: Unable to start service org.qiyi.pluginlibrary.component.ServiceProxy1@d68f884 with Intent { act=org.qiyi.plugin.library.START_PLUGIN cmp=com.shijc.neptunedemo/org.qiyi.pluginlibrary.component.ServiceProxy1 (has extras) }: java.lang.IllegalStateException: pluginLiteInfo is null when launchPlugin com.shijc.search
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3596)
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:171)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6699)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
                                                  Caused by: java.lang.IllegalStateException: pluginLiteInfo is null when launchPlugin com.shijc.search
                                                     at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:533)
                                                     at org.qiyi.pluginlibrary.runtime.PluginManager.launchPlugin(PluginManager.java:422)
                                                     at org.qiyi.pluginlibrary.component.ServiceProxy1.onStartCommand(ServiceProxy1.java:227)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3576)
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:171) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6699) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
10-09 15:09:35.675 8822-9200/? E/libc: Access denied finding property "persist.service.bdroid.bdaddr"
10-09 15:09:36.062 8822-9263/? E/libc: Access denied finding property "ro.serialno"

**Comment by shijiacheng** [comment]
请问咱们有交流群或者反馈群吗？这样有问题就可以及时反馈了。

**Comment by tianhongyan** [comment]
11-26 18:30:03.669 7479-7479/com.iqiyi.host.sample I/runtime_plugin: [ ComponentFinder ] : matchServiceProxyByFeature:org.qiyi.pluginlibrary.component.ServiceProxy1
11-26 18:30:04.217 7479-11422/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : setActionFinishCallback with process name: com.iqiyi.host.sample:plugin1
11-26 18:30:04.218 7479-11422/com.iqiyi.host.sample I/install_plugin: [ PluginPackageManager ] : packageAction , com.iqiyi.plugin.sample installed : true installing: false
11-26 18:30:04.223 7479-7499/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : getPackageInfo com.iqiyi.plugin.sample return null due to sPluginInfoProvider is null
11-26 18:30:04.232 7479-7499/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : getPackageInfo com.iqiyi.plugin.sample return null due to sPluginInfoProvider is null
11-26 18:30:04.233 7479-7499/com.iqiyi.host.sample I/runtime_plugin: [ PluginPackageManager ] : getPackageInfo from local cache

**Comment by zjupure** [comment]
It should be fixed in 2.7.0 release
